name: Release package

env:
  NUGET_SOURCE_URL: https://nuget.pkg.github.com/AndrewMJordan
  NUGET_PROJECT_DIR: src/Play/Play.csproj

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          source-url: ${{env.PACKAGE_REGISTRY}}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: |
          dotnet build --configuration Release "${{env.NUGET_PROJECT_DIR}}"
          dotnet pack --configuration Release "${{env.NUGET_PROJECT_DIR}}" --no-build --output .
          dotnet nuget push *.nupkg --api-key ${{secrets.GITHUB_TOKEN}}
